name: EAS Updates

on:
  push:
    branches: ['main']

jobs:
  send_updates:
    if: contains(github.event.head_commit.message, 'push:')
    name: EAS Send updates
    type: update
    params:
      channel: production
